### ISSUE TITLE
Enable editing of JSON files from within the Resources tab

### ISSUE THREAD

**Issue by davidasbury** [EsriPS/arcgis-assistant-feedback#15]
First of all, congratulations and thanks so much for refreshing ago-assistant and providing great documentation!

This suggestion pertains specifically to editing ArcGIS StoryMaps, but would be applicable to other items as well.

Since the [recommended workflow](https://guide.assistant.esri-ps.com/docs/common-workflows#editing-story-data-json) to edit a story's JSON is to modify the draft_xxxxxxx.json file and then use the AGSM builder to publish the changes, it would be nice to be able to edit draft_xxxxxx.json within ArcGIS Assistant. 

As of now you need to download draft_xxxxxx.json make your edits and then upload/replace the file under the Resources tab.

A shortcut under the ellipsis icon that opens draft_xxxxxx.json in the JSON Monaco Editor would be very helpful.

![image](https://user-images.githubusercontent.com/6776067/126695937-cdb5aa1b-41fc-4ba8-8456-a57794459bc8.png)

Thanks again!

**Comment by jpeterson** [comment]
Hey @davidasbury! It just so happens this is already in progress 😄 

I'll update this issue as soon as we have it ready.

And all credit for the great ArcGIS StoryMaps workflows goes to @oevans!

**Comment by jpeterson** [comment]
Hi @davidasbury, just wanted to let you know [a fresh version of Assistant](https://assistant.esri-ps.com/) is out and supports Item Resource editing! 

You can edit **JSON files** (support for XML coming soon) in the browser by clicking the file name on the screen you captured above.

Let us know how it works for you!

**Comment by davidasbury** [comment]
@jpeterson This is great, thanks! 

Would still be nice to have a shortcut to the editor from the ellipses icon at some point - but this goes a long way to making things easier!
