### ISSUE TITLE
Esri Professional Services link from the Guide points to the Geoinformation Model. 

### ISSUE THREAD

**Issue by jmirmelstein** [EsriPS/arcgis-assistant-feedback#20]
From the [ArcGIS Assistant User Guide](https://guide.assistant.esri-ps.com/), in the About Assistant section - the hyperlink for Esri Professional Services points to the same link as the ArcGIS geoinformation model.

**Comment by jpeterson** [comment]
Removed this hyperlink (https://github.com/EsriPS/arcgis-assistant-feedback/commit/953df0f05c28c47b0541a801ce8931f798fd9c24) until we can figure out the docusaurus bug that was causing it.
