### ISSUE TITLE
Same Username for Portal and AGOL

### ISSUE THREAD

**Issue by mripp** [EsriPS/arcgis-assistant-feedback#21]
**Describe the bug**
When a user logins to ArcGIS Assistant with the same username for both Portal and ArcGIS Online it prevents the person from having multiple accounts logged in at the same time. It switches to the current system. Thus I am unable to copy items from one account to the other.

**To Reproduce**
1. Go to https://assistant.esri-ps.com/
2. Sign in with ArcGIS Online. Username = mmontelongo
3. Click on the username in the upper right and add an Enterprise Account
4. Add the portal URL and App ID
5. Sign in with Enterprise account. Username - mmontelongo (Note this login is setup with an Enterprise login)
6. ArcGIS Online assistance logs into Enterprise but I am no longer logged into ArcGIS Online

**Expected behavior**
I am expecting to be logged into both ArcGIS Online and ArcGIS Enterprise. If you login to Enterprise first and then ArcGIS Online it does the same behavior

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Enterprise 10.8.1

**Additional context**
This happened with my customer from Whataburger

**Comment by jpeterson** [comment]
Thanks for reporting this, @mripp! We're looking into it and will update this issue when we have more info to share.

**Comment by geompc** [comment]
We're seeing the same thing except going from 10.8.1 Enterprise pre-prod to 10.8.1 prod, using built in accounts. Same username for both.

**Comment by jpeterson** [comment]
Thanks for this additional finding, @geompc, we'll check in on this scenario as well.

**Comment by brandonlammey** [comment]
This appears to be an issue with the [calcite-react account manager](https://calcite-react.netlify.app/arcgis-account). Accounts are currently identified by an accountId which is structured as {user.name}-{portal.name}. portal.name may not be unique between Enterprise portals and AGOL orgs. This will cause issues with tracking multiple accounts with identical user names in different Portals/Orgs. This will be addressed in the [createAccountKey](https://github.com/Esri/calcite-react/blob/2b74384aa21088befd1bc9c852ebe468be545674/src/ArcgisAccount/accountManagerUtils.js#L323) function in calcite-react. We will look into a method to uniquely identify accounts.
