### ISSUE TITLE
Copied Web AppBuilder applications have the wrong edit link

### ISSUE THREAD

**Issue by cmartin616** [EsriPS/arcgis-assistant-feedback#26]
**Describe the bug**

**To Reproduce**
1. Go to 'https://assistant.esri-ps.com'.
2. Sign in
3. Select WAB app
4. Select Copy Items
5. New item {item_name} (copy) is created.
6. Item has new item ID but 'Edit Application' link has original item ID

**Expected behavior**
Edit Application link should point to the new item ID

**Screenshots**
![image](https://user-images.githubusercontent.com/6685997/135151625-34f3efaf-646c-4553-898f-1d337cc2ae7f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 92.0

**Additional context**

**Comment by jpeterson** [comment]
This issue should be resolved with today's release!

https://guide.assistant.esri-ps.com/docs/changelog#1-november-2021
