### ISSUE TITLE
No longer able to edit copied content

### ISSUE THREAD

**Issue by JLogSD** [EsriPS/arcgis-assistant-feedback#36]
**Describe the bug**
Content I copy over to my Portal, whether from my organization or a public source, is no longer editable. When using this application a few weeks ago, I was able to copy content like this and had full editing rights. Now, when it is copied over a popup appears asking for my AGO login information. Even if I login, I don't have editing rights. I'm unable to view details in the REST services page as well.

**To Reproduce**
1. Sign into ArcGIS [Assistant Beta](https://assistant.esri-ps.com/signin) with my AGO and my Portal account.
2. Select layer from my AGO account or public source.
3. Copy content over to my Portal account.
4. Open copied content on Portal.
5. Met with AGO login window.
6. Sign with AGO credentials.
7. Unable to add/edit fields in Data tab.
8. Unable to view info on Rest Services page.

**Expected behavior**
I expect to have full editing rights of content I copy over to my Portal account. I don't expect to have to login into my AGO account when accessing copied data in my Portal.

**Screenshots**

![Prompt to login to AGO on Portal content](https://user-images.githubusercontent.com/93403244/143085307-57f54164-7b2e-4463-9373-aa86bff1b303.png)

![Error message when trying to view fields in Data tab in Portal](https://user-images.githubusercontent.com/93403244/143085445-fac5066e-7ef6-4242-b7f6-9b331e9eb760.png)

![Unable to view REST services info](https://user-images.githubusercontent.com/93403244/143085557-7e4f3d1d-b8d7-4f62-aeee-43bb6af7f7fb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 1909
 - Browser: Google Chrome 96.0.4664.45

**Additional context**
I no longer can use your [old ArcGIS Online Assistant](https://ago-assistant.esri.com/) for this. I get error 400 when logging into Portal.

**Comment by slibby** [comment]
What is the URL listed for the item in your Portal after copying it over? If it is an ArcGIS Online item and that service is secured, then what you are seeing is expected. I think what you are expecting is "full copy" from the old ago-assistant, which is still on the roadmap and not yet implemented.

**Comment by JLogSD** [comment]
@slibby 
You're right, I was expecting a full copy with the new Assistant. My bad!
Thanks!
