### ISSUE TITLE
Incorrect information in "App ID" hint (i) with ArcGIS Enterprise login

### ISSUE THREAD

**Issue by StaEsri** [EsriPS/arcgis-assistant-feedback#4]
**Describe the bug**
When logging in to an ArcGIS Enterprise portal from https://assistant.esri-ps.com/content, the Redirect URI's hint shown at the (i) at the "App ID" field incorrectly states to add the https://assistant.esri.com URI in you application instead of the correct URI: https://assistant.esri-ps.com

**To Reproduce**
Create an APP ID in your Enteprise portal, adding https://assistant.esri.com to the Redirect URI's field as suggested/shown will result in the error "Invalid redirect_uri / error 400"

**Screenshots**

![image](https://user-images.githubusercontent.com/82816311/115234684-9c17ec80-a119-11eb-93cc-91c5bef44fbe.png)

![image](https://user-images.githubusercontent.com/82816311/115235349-60c9ed80-a11a-11eb-9a40-6815817864df.png)

**Comment by jpeterson** [comment]
Thanks for catching this @StaEsri!

**Comment by jpeterson** [comment]
This is fixed! https://guide.assistant.esri-ps.com/docs/changelog
