### ISSUE TITLE
Unable to save JSON Edits 

### ISSUE THREAD

**Issue by susanhmel-doit** [EsriPS/arcgis-assistant-feedback#52]
When trying to edit the data JSON for a webmap, the save button is greyed out and the edits cannot be saved. 

This happens when going to the JSON Editor in the Assistant and clicking "Edit JSON". Edits can be made to the JSON text but can not be saved. The JSON validation is passing - no JSON errors are showing. 

I haven't test all item types, but so far this is an issue in webmaps, dashboard apps, and instant apps.

Noting that this issue started happening to us on Friday, 9/2 and has not resolved since. 

![image](https://user-images.githubusercontent.com/63746611/191578267-7e9a1a09-9840-4dc9-a5dd-bcecbafeb859.png)

Found this issue in Chrome, Edge, and Firefox browsers and multiple computers.

**Comment by jpeterson** [comment]
Thanks for reporting this, @susanhmel-doit. Sorry it's been causing you trouble for a few weeks now!

I am not able to reproduce your issue after trying with a few different test accounts, which indicates there may be something happening specific to your organization or user that Assistant doesn't know how to handle yet. 

I'm hoping you can run through these 3 steps and report back!

1. Double-check that [the active account in Assistant](https://guide.assistant.esri-ps.com/docs/working-with-accounts#the-active-account) has permission to edit the item(s) in question

2. If the user definitely can edit the item, is there anything advanced about this scenario? For example, is edit permission being granted [via a collaboration](https://doc.arcgis.com/en/arcgis-online/administer/understand-collaborations.htm), or does the user have a custom role that might be causing Assistant to misbehave?

3. If the above all checks out, using your [browser developer tools](https://balsamiq.com/support/faqs/browserconsole/#google-chrome), open the console tab. Reproduce the issue and note any messages that get logged in the console.

If you can share your results, hopefully, we can narrow down what's going on here. Thanks!

**Comment by susanhmel-doit** [comment]
Thanks for the quick response! After testing in a few locations, computers, and orgs - another teammate in our Org tried the same updates in the organization and was able to get it to work. When I tried again soon after, the save button is no longer greyed out and allowed me to save. Not sure what may have caused the issue, but I know that the active account had permission as it owned the webmap. Also, when saving was not working on the JSON editor, I was still able to edit using the older AGO Assistant tool. 

Not sure what caused the mystery of the unavailable save button, but all of the saving seems to be working now! 

Thanks,
Susan
