### ISSUE TITLE
If I try to copy certain items, Workforce Project, the JSON data is not copied

### ISSUE THREAD

**Issue by roemhildtg** [EsriPS/arcgis-assistant-feedback#6]
**Describe the bug**

I just tried copying a workforce project item ( I wanted to back up the JSON content). Instead of duplicating the item with the json data, the new item was created but it was empty when navigating to the Data tab in AGO Assistant. 

**To Reproduce**
Open AGO Assistant
Navigate to a workforce project item
Choose to copy
View the copied items data - it is empty

**Expected behavior**
Items that are copied should have the json data from their parent. 

**Desktop (please complete the following information):**
MacOS
Vivaldi (chrome)

**Additional context**

**Comment by jpeterson** [comment]
Thanks for letting us know about this one @roemhildtg! We'll look into it and let you know what we discover.

**Comment by roemhildtg** [comment]
Sounds good - btw awesome job on the new ui. Looks great and it is very intuitive and fast!

**Comment by jpeterson** [comment]
@roemhildtg this issue should be resolved as of [yesterday's release](https://guide.assistant.esri-ps.com/docs/changelog#11-may-2021)!

Please let us know if you still see any issues.

**Comment by roemhildtg** [comment]
Thanks @jpeterson ! What a quick turnaround!

A side question - any plans to release the code for this project? It could be useful for other devs to use as a tool to help modify items in environments where a portal is air-gapped for instance. 

Also I could see using it as an example to help learn the ArcGIS rest api - and how to develop applications around it. This app seems like one of the best implementations of an ArcGIS REST API Application and could be useful to devs everywhere.

Third - I think its a project that could be extended by devs who'd like to submit pull requests for new features/etc. 

Just my two cents :)

**Comment by jpeterson** [comment]
> Thanks @jpeterson ! What a quick turnaround!

👍🏼 and 🙏🏼  to @thollingshead! 

> A side question - any plans to release the code for this project? It could be useful for other devs to use as a tool to help modify items in environments where a portal is air-gapped for instance.

We definitely plan to release a version that can be deployed (and be sure it supports disconnected environments), in fact we're actively working on this.

> Also I could see using it as an example to help learn the ArcGIS rest api - and how to develop applications around it. This app seems like one of the best implementations of an ArcGIS REST API Application and could be useful to devs everywhere.
>
> Third - I think its a project that could be extended by devs who'd like to submit pull requests for new features/etc.
> 
> Just my two cents :)

❤️ and agreed on all points! We are still checking off some boxes internally before going ahead and fully open sourcing, but that is our goal 🙂
