### ISSUE TITLE
Issues with jumping to last page of Item Resource list if viewing 100 at a time

### ISSUE THREAD

**Issue by kerryrobinson** [EsriPS/arcgis-assistant-feedback#7]
**Describe the bug**
For items that have many resources (i.e. dictionary web style... over 8000 in this one: https://assistant.esri-ps.com/item/75b40938249848dcaa7a9f3a8fec2895/resources?), I have found that if I choose to show 100 items per page, but then click on the last page in the list, it reverts back to 20 items per page. 

**To Reproduce**
1. Go to the item resource page for a dictionary web style (https://assistant.esri-ps.com/item/75b40938249848dcaa7a9f3a8fec2895/resources?)
2. Click on `Items per page: 100`
3. Click on the very last page in the list (84)
4. Notice that it reverts back to 20 items per list (note this does not happen if you step through one page at a time, the issue only occurs when jumping to the last page)

**Expected behavior**
In addition to the ability to [search](https://github.com/EsriPS/arcgis-assistant-feedback/issues/3) items with many resources, the ability to page through 100 items at a time is needed so that you can more easily find items you're looking for.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
The ability to sort does help out with this issue.

**Comment by jpeterson** [comment]
Thanks for catching this @kerryrobinson, we'll take a look. 

cc: @alexanderela

**Comment by jpeterson** [comment]
@kerryrobinson – this issue should be fixed now. [Here's the changelog from today](https://guide.assistant.esri-ps.com/docs/changelog#25-may-2021). Let us know if you're still experiencing issues!

**Comment by kerryrobinson** [comment]
@jpeterson Yes, looking good. Thank you!
