### ISSUE TITLE
Page Navigation and Item Display options not working

### ISSUE THREAD

**Issue by JoshALogs** [EsriPS/arcgis-assistant-feedback#77]
**Describe the Bug**
I'm experiencing issues with page navigation and item display options in ArcGIS Assistant. Clicking on different page numbers or changing the number of items to display per page does not yield any changes. The only workaround is altering the URL parameters for item count, but page navigation remains non-functional.

**To Reproduce**
 
1. Go to ArcGIS Assistant and sign in (either personal or organization account).
2. Navigate to "All Content" (I have 150 total items in my account).
3. Attempt to click the page numbers at the bottom; observe no change or loading activity.
4. Attempt to change the number of items to display using the dropdown at the bottom; observe no change or loading activity.
5. Manually adjust the URL parameter for items to display; observe that the page will load with that count (though 100 is the max).

**Expected Behavior**
I expect to navigate to different pages to view different sets of items. Additionally, changing the number of items to display from the dropdown at the bottom should reload the page with the new item count.

**Screenshots**
![image](https://github.com/EsriPS/arcgis-assistant-feedback/assets/31683291/c3817685-5a0b-4351-ba32-4fae93e049b6)
I can select the page, but the displayed content does not change.

**Desktop**

- OS: Windows 11
- Browser: Firefox 117.0.1 (64-bit), Microsoft Edge Version 117.0.2045.36 (64-bit)

**Additional Info**
I can still copy items I see/select to other accounts, but only up to the first 100 items I can view.

**Comment by jpeterson** [comment]
Hi @JoshALogs, thanks for making this issue. We've been working to get Assistant's UI moved over to [Calcite Design System](https://developers.arcgis.com/calcite-design-system/), so this particular issue has been lingering. Good news though, a fix is in the works 🙂 

Would you mind testing out your workflow in our dev environment? You can find it here: https://dev.assistant.esri-ps.com (note the build date in the header). Note that this environment receives updates more often and may not be as stable as https://assistant.esri-ps.com. We are working on pushing an update to the primary Assistant app soon.

**Comment by JoshALogs** [comment]
Hi @jpeterson, thanks for help on this. I tested with several accounts and the dev env is working much better here; the page responds to the navigation buttons and number of items to display is now working.

I noticed this as well:
In the dev env, my currently active account has 100+ items, and I set the "Items per page" to 100. If I switch the active account to one with less than 100 items, all of my items will be displayed for this account, but the "Items per page" element will not appear at all on the bottom of the page. I would expect the options for "20, 60, 100" to appear still. It's no issue, but thought it might be a small UI bug.

Also, it looks like the progress element is working in this env as well. In the prod env, this element would always just say "Copying", even when the job was finished. In dev, it now tells me it finished as expected:
![image](https://github.com/EsriPS/arcgis-assistant-feedback/assets/31683291/4c6e906d-0af0-483b-b6b0-d6dd80b2bf39)

Thanks again for getting back so quickly on this.
BTW, will the assistant ever support full copy support for feature services?

**Comment by jpeterson** [comment]
Thanks for confirming the pagination fix, @JoshALogs! I've noted the issue you mentioned when switching accounts as well (#78), thanks for that.

As far as full copy (or cloning or deep copying) for feature services... that is actually in progress as well 🙂 If you'd like to give it a go, you're welcome to – we have an early test build here: https://pr-417.assistant.esri-ps.com/ (note the pagination fix has not been incorporated into this build yet).
