### ISSUE TITLE
Organization Items not Displaying

### ISSUE THREAD

**Issue by runneals** [EsriPS/arcgis-assistant-feedback#9]
**Describe the bug**
No items show up when I'm logged in as an admin and try to click on the [Organization tab](https://assistant.esri-ps.com/content?queryScope=ORGANIZATION&folder=allmycontent&focus=maps&num=20&start=1&sortField=modified&sortOrder=desc)

**Comment by jpeterson** [comment]
Thanks for logging this @runneals! Luckily @alexanderela already had a fix in the works 😉 

The issue should be fixed as of today's update. [Here's the changelog from today](https://guide.assistant.esri-ps.com/docs/changelog#25-may-2021). Let us know if you're still experiencing issues!
